config/routes.rb
Rails.application.routes.draw do

  # topPage
  root 'tops#index'
  get 'tops/index'
  post '/tops/guest_sign_in', to: 'tops#new_guest'

  # session関連
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # ＋SNSログイン
  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'

  # user関連
  resources :users

  # petsitter関連
  resources :petsitters do
    # like(いいね)関連
    resources :likes, only: [:create, :destroy]
    # temp_save(一時保存)関連
    resources :temp_saves, only: [:create, :destroy]
  end

  get 'users/:id/histories', to: 'users#histories', as: 'user_histories'
  get 'users/:id/clips', to: 'users#clips', as: 'user_clips'
  get 'petsitters/:id/details', to: 'petsitters#details', as: 'petsitter_details'
  get 'petsitters/:id/reviews', to: 'petsitters#reviews', as: 'petsitter_reviews'
  get 'petsitters/:id/reviews/new', to: 'petsitters#postReviews', as: 'petsitter_new_reviews'
  get 'petsitters/:petsitter_id/reviews/:review_id', to: 'reviews#edit', as: 'edit_reviews'
  get 'petsitters/:id/map', to: 'petsitters#map', as: 'petsitter_map'

  # review関連
  resources :reviews, only: [:create, :update, :destroy]

end

app/models/petsitter.rb
class Petsitter < ApplicationRecord
  # 書く順番
  # ①アソシエーション（belongs_toなど）
  # ②gemなどの関数や他の定義
  # ③AttributeMethodsモジュール
  # ④attr関連
  # ⑤バリデーション
  # ⑥コールバック

  # 関連付け
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :temp_save, dependent: :destroy
  has_many :temp_saved_users, through: :temp_save, source: :user

  # 画像投稿用（carrierwave使用）
  mount_uploader :image, ImageUploader

  # phone用の正規表現
  VALID_PHONE_REGEX = /\A[0-9]{2,3}[-0-9][0-9]{3,4}[-0-9][0-9]+\z/i

  # Validation
  validates :name, { presence: true, length: { maximum: 30 }}
  validates :address, { presence: true}
  validates :prefecture, { presence: true}
  validates :town, { presence: true}
  validates :phone, { presence: true, length: { maximum: 15 }, format: { with: VALID_PHONE_REGEX }}
  validates :pet_type, { presence: true}
  validates :insurance, { presence: true}
  validate :validate_name_not_including_comma

  private
  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

app/controllers/petsitters_controller.rb
class PetsittersController < ApplicationController
  protect_from_forgery :except => [:postReviews, :create, :update, :destroy]
  before_action :make_address, only: [:create, :update]
  before_action :regular_holiday_string, only: [:create, :update]
  before_action :pet_type_string, only: [:create, :update]
  before_action :admin_user, only:[:new, :create, :edit, :update, :destroy]
  before_action :set_petsitter, only:[:show, :details, :reviews, :postReviews,:map] # 企業詳細ページの共通処理
  skip_before_action :login_required, only: [:index, :show, :details, :reviews, :map]
  include PetsittersHelper
  PER = 5

  # ペットシッター一覧表示
  def index
    # 検索
    @q = Petsitter.ransack(params[:q])
    # 検索に引っ掛かったペットシッターをページネーション加工したもの
    @petsitters = @q.result(distinct: true).page(params[:page]).per(PER)

    # searched_petsitters_countは検索に引っ掛かったペットシッターの数
    @searched_petsitters_count = @q.result(distinct: true)&.count
  end

  # ペットシッター新規登録ページ表示
  def new
    @petsitter = Petsitter.new
  end

  # ペットシッター新規登録処理
  def create
    # ストロングパラメーターを使用してペットシッターインスタンス生成
    @petsitter = Petsitter.new(petsitter_params)
    if @petsitter.save
      # ペットシッター登録成功した場合
      redirect_to root_path, notice: "ペットシッター登録が完了しました。"
    else
      # ペットシッター登録失敗した場合
      flash.now[:alert] = 'ペットシッター登録が失敗しました。'
      render :new
    end
  end

  # ペットシッター編集ページ表示
  def edit
    @petsitter = Petsitter.find(params[:id])
  end

  # ペットシッター更新処理
  def update
    @petsitter = Petsitter.find(params[:id])
    if @petsitter.update(petsitter_params)
      redirect_to root_path, notice: "ペットシッター情報を更新しました。"
    else
      flash.now[:alert] = 'ペットシッター情報更新に失敗しました。'
      render :edit
    end
  end

  # ペットシッター削除処理
  def destroy
    @petsitter = Petsitter.find(params[:id])
    @petsitter.destroy
    redirect_to root_path, notice: "ペットシッター情報を削除しました。"
  end

  # ペットシッター詳細表示
  def show
  end

  def details
  end

  def reviews
    # 新規レビュー用インスタンス
    @review = Review.new

    # reviewコントローラーなどで使うため@petsitter.idをsessionに保存
    session[:petsitter_id] = @petsitter.id
  end

  def postReviews
    # 新規レビュー用インスタンス
    @review = Review.new

    # reviewコントローラーなどで使うため@petsitter.idをsessionに保存
    session[:petsitter_id] = @petsitter.id

    # 自分のコメントがあるかチェックする
    @is_my_review = @reviews.find_by(user_id: current_user.id)
  end


  def map
    # マップ（mapに移管する予定）
    # 以下はGoogleMapテスト
    gon.address = @petsitter.address
  end

  # 住所作成処理
  def make_address
    # パラメーターの加工
    # 住所加工
    prefecture = params.require(:petsitter)[:prefecture]
    town = params.require(:petsitter)[:town]
    block = params.require(:petsitter)[:block]
    apartment = params.require(:petsitter)[:apartment]
    params.require(:petsitter)[:address] = prefecture + town + block + apartment
  end

  # 定休日の配列を文字列にする（/区切り）
  def regular_holiday_string
    params[:petsitter][:regular_holiday] = params[:petsitter][:regular_holiday]&.join("/")  || "" # to string
  end

  # 対応可能動物の配列を文字列にする（、区切り）
  def pet_type_string
    params[:petsitter][:pet_type] = params[:petsitter][:pet_type]&.join("、")  || "" # to string
  end

  private
  # ストロングパラメーター（ペットシッターパラメーター取得用）
  def petsitter_params
    params.require(:petsitter).permit(
        :name,
               :url,
               :address,
               :prefecture,
               :town,
               :block,
               :apartment,
               :area,
               :phone,
               :business_hours,
               :regular_holiday,
               :pet_type,
               :overview,
               :qualification,
               :registration_number,
               :insurance,
               :image,)
  end

  # 管理者権限有無の確認
  def admin_user
    @users = User.all
    if  current_user.admin == false
      flash[:alert] = 'この操作には管理者権限が必要です。'
      redirect_to root_path
    end
  end

  # 企業詳細ページの共通処理
  def set_petsitter
    # 該当のペットシッターを検索
    @petsitter = Petsitter.find(params[:id])

    # 新規いいね用インスタンス
    @like = Like.new

    # 新規一時保存用インスタンス
    @temp_save = TempSave.new

    # 該当のペットシッターIDで検索できるレビューを取得
    @reviews = Review.where(petsitter: @petsitter.id)
  end

end

app/helpers/petsitters_helper.rb
module PetsittersHelper


  # ユーザーIDからユーザー名を取得するメソッド
  def getUserNameByUserId(user_id)
    user_name = User.find(user_id).name
    return user_name
  end

  # ペットシッターIDからペットシッター情報を取得するメソッド
  def getPetsitterByPetistterId(petsitter_id)
    petsitter = Petsitter.find(petsitter_id)
    return petsitter
  end

  # ユーザーIDからユーザー情報を取得するメソッド
  def getUserByUserId(user_id)
    user = User.find(user_id)
    return user
  end

end

app/views/petsitters/_shopHeader.html.erb
<!-- ペットシッター詳細の上部部分-->
<div class="breadcrumbs-list">
  <%= render "shared/breadcrumbs" %>
</div>
<div class="shop-header">
  <div class="info-wrap">
    <div class="shop-controller">
      <% if @petsitter.url %>
        <div class="shop-name"><%= link_to @petsitter.name, @petsitter.url, class:'shop-name-with-link' %></div>
      <% else %>
        <div class="shop-name"><%= @petsitter.name %></div>
      <% end %>
    </div>
    <div class="shop-top-info">
      <div class="shop-top-info_rate"><%= render partial: 'layouts/rate' %></div>
      <div class='shop-top-info_reviews'>
        <%# ここにcontrollerActionの分岐で入るようにする %>
        <%= link_to petsitter_reviews_path(@petsitter.id) do %>
          <i class='fas fa-comment-dots'></i><% if @petsitter&.reviews %><%= @petsitter.reviews.count %><% else %>0<% end %> 件
        <% end %>
      </div>
      <div class='shop-top-info_bookmarks'>
        <% if current_user != nil %>
          <% if current_user.already_liked?(@petsitter) %>
            <%= link_to petsitter_like_path(@petsitter.id, current_user.id), method: :delete do %>
              <i class='fas fa-bookmark'></i><% if @petsitter&.liked_users %><%= @petsitter.liked_users.count %><% else %>0<% end %> 件
            <% end %>
          <% else %>
            <%= link_to petsitter_likes_path(@petsitter.id), method: :post do %>
              <i class='fas fa-bookmark'></i><% if @petsitter&.liked_users %><%= @petsitter.liked_users.count %><% else %>0<% end %> 件
            <% end %>
          <% end %>
        <% else %>
          <%= link_to petsitter_likes_path(@petsitter.id), method: :post do %>
            <i class='fas fa-bookmark'></i><% if @petsitter&.liked_users %><%= @petsitter.liked_users.count %><% else %>0<% end %> 件
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="shop-bottom-info">
      <span>エリア：</span>
      <%# TODO 、でareaの部分の文字を分裂させる %>
      <% @petsitter.area.split(/、/).each do |area| %>
        <%= link_to area, petsitters_path(@q, :'q[area_cont' => "#{area}") %>&nbsp;
      <% end %>
      <span class="pet-type">対応可能動物種類：</span>
      <div class='pet-types'>
        <ul class='pet-types-list'>
          <% @petsitter.pet_type.split(/、/).each do |pet_type| %>
            <%= link_to pet_type, petsitters_path(@q, :'q[name_or_pet_type_cont' => "#{pet_type}") %>&nbsp;
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class='action-wrap'>
    <div class='action-wrap_app'>
      <!-- 口コミ投稿 -->
      <div class='action-btn' id='testsample'>
        <% if current_user != nil %>
            <%= link_to petsitter_new_reviews_path(@petsitter.id), class:'action-link' do %>
              <i class='fas fa-user-check fa-lg'></i> <span class='action-name'>行った</span>
            <% end %>
        <% else %>
          <%= link_to petsitter_new_reviews_path(@petsitter.id), class:'action-link' do %>
            <i class='fas fa-bookmark fa-lg'></i> <span class='action-name'>行った</span>
          <% end %>
        <% end %>
      </div>
      <!-- bookmark -->
      <div class='action-btn' id='testsample'>
        <% if current_user != nil %>
          <% if current_user.already_liked?(@petsitter) %>
            <%= link_to petsitter_like_path(@petsitter.id, current_user.id), class:'action-link', method: :delete do %>
              <i class='fas fa-bookmark fa-lg'></i> <span class='action-name'>保存</span>
            <% end %>
          <% else %>
            <%= link_to petsitter_likes_path(@petsitter.id), class:'action-link', method: :post do %>
              <i class='fas fa-bookmark fa-lg'></i> <span class='action-name'>保存</span>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to petsitter_likes_path(@petsitter.id), class:'action-link', method: :post do %>
            <i class='fas fa-bookmark fa-lg'></i> <span class='action-name'>保存</span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/petsitters/details.html.erb
<%= render partial: 'petsitters/shopHeader' %>
<ul class="shop-menu-bar">
  <li class="shop-menu-link"><%= link_to "店舗トップ", petsitter_path %></li>
  <li class="shop-menu-link selected-menu"><%= link_to "詳細", petsitter_details_path %></li>
  <li class="shop-menu-link"><%= link_to "口コミ", petsitter_reviews_path %></li>
  <li class="shop-menu-link"><%= link_to "地図", petsitter_map_path %></li>
</ul>

<div class="shop-content">
  <!-- 詳細 -->
  <div class="shop-content_details">
    <div class="items-wrapper">
      <div class="item-area">
        <div class="item-area_heading">店舗名</div>
        <div class="item-area_content"><%= @petsitter&.name %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">URL</div>
        <div class="item-area_content"><%= @petsitter&.url %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">電話番号</div>
        <div class="item-area_content"><%= @petsitter&.phone %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">住所</div>
        <div class="item-area_content"><%= @petsitter&.address %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">営業日</div>
        <div class="item-area_content"><%= @petsitter&.regular_holiday %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">営業時間</div>
        <div class="item-area_content"><%= @petsitter&.business_hours %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">対応可能動物</div>
        <div class="item-area_content"><%= @petsitter&.pet_type %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">保有資格</div>
        <div class="item-area_content"><%= @petsitter&.qualification %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">登録番号</div>
        <div class="item-area_content"><%= @petsitter&.registration_number %></div>
      </div>
      <div class="item-area">
        <div class="item-area_heading">ペットシッター保険</div>
        <div class="item-area_content"><%if @petsitter&.insurance %>有<% else %>無<% end %></div>
      </div>
    </div>
  </div>
</div>

app/views/petsitters/edit.html.erb
<%= render partial: 'form', locals: { petsitter: @petsitter } %>

app/views/petsitters/index.html.erb
<%= render partial: '/layouts/petsittersIndexHeader' %>
<div class="petsitter-store-contents">
  <ul class="petsitter-store-content">
    <!-- ペットシッター一覧 -->
    <% @petsitters.each do |petsitter| %>
      <%= link_to petsitter_path(petsitter.id), class:'shop-link' do %>
        <div class="top-info">
          <div class="top-info_name-and-area">
            <li class= 'top-info_name-and-area_name'><%= petsitter.name %></li>
            <li class='top-info_name-and-area_area'><%= petsitter.area %>／<%= petsitter.pet_type %></li>
          </div>
          <% if current_user.blank? != true && current_user.admin == true %>
            <div class="admin_user_option">
              <%= link_to "編集", edit_petsitter_path(petsitter.id) %>
              <%= link_to "削除", petsitter_path(petsitter.id), method: :delete %>
            </div>
          <% end %>
          <div class="top-info_action-buttons">
            <!-- reviewのアイコン＋レビューの数 -->
            <div class="action-icon action-icon_left">
              <% if current_user_reviewd_this_petsitter?(petsitter.id) %>
                <i class="fas fa-user-check fa-lg user-count-<%= petsitter.reviews.count %>"></i><span><%= petsitter.reviews.count %></span>
              <% else %>
                <i class="fas fa-user-check fa-lg user-count-0"></i>
              <% end %>
            </div>
            <!-- bookmarkのアイコン＋ブックマークされた数 -->
            <div class="action-icon">
              <% if current_user_liked_this_petsitter?(petsitter.id) %>
                <i class="fas fa-bookmark fa-lg clip-count-<%= petsitter.likes.count %>"></i>
              <% else %>
                <i class="fas fa-bookmark fa-lg clip-count-0"></i>
              <% end %>
            </div>
          </div>
        </div>

        <div class="bottom-info">
          <div class="bottom-info_left">
            <% if petsitter&.image.blank? %>
              <%= image_tag 'default.jpg', class:'samplesample' %>
            <% else %>
              <%= image_tag petsitter&.image.url, class:'samplesample' %>
            <% end %>
          </div>

          <div class="bottom-info_right">
            <div class="bottom-info_right_overview">
              <%= petsitter&.overview&.truncate(90, omission: '...') %>
            </div>
            <div class="bottom-info_right_rating">

              <!--星評価-->
              <div id="sample-star-rate-<%= petsitter.id %>" class="shop-star-rate"></div>
              <script>
                  $('#sample-star-rate-<%= petsitter.id %>').raty({
                      size: 16,
                      half: true,
                      starOff:  '<%= asset_path('star-off-little.png') %>',
                      starOn : '<%= asset_path('star-on-little.png') %>',
                      starHalf: '<%= asset_path('star-half-little.png') %>',
                      // half: true,
                      readOnly: true,
                      score: "<%= petsitter&.reviews.average(:rate).to_f.round(2) || 0 %>",
                  });
              </script>
              <div class="shop-rating"><%= petsitter&.reviews.average(:rate).to_f.round(2) || 0 %></div>
              <!--/星評価-->

              <!-- 口コミ投稿 -->
              <div class="shop-count">
                <i class='fas fa-comment-dots'></i><span class="shop-count_text"><%= petsitter.reviews.count %>件</span>
              </div>
              <!-- bookmark -->
              <div class="shop-count">
                <i class='fas fa-bookmark'></i><span class="shop-count_text"><%= petsitter.likes.count %>件</span>
              </div>
            </div>

            <!-- レビューがない場合はデフォルト表示。あればレビューを表示。 -->
            <% if petsitter.reviews.blank? %>
              <div class="bottom-info_right_top_review">
                <div class="bottom-info_right_top_review_title-and-user">
                  <div class="bottom-info_right_top_review_title-and-user_title">口コミ未投稿</div>
                  <div class="bottom-info_right_top_review_title-and-user_user">by</div>
                </div>
                <div class="bottom-info_right_top_review_content">まだ口コミが投稿されていません</div>
              </div>
            <% else %>
              <div class="bottom-info_right_top_review">
                <div class="bottom-info_right_top_review_title-and-user">
                  <div class="bottom-info_right_top_review_title-and-user_title"><%= petsitter.reviews.last.title %></div>
                  <div class="bottom-info_right_top_review_title-and-user_user">by <%= getUserNameByUserId(petsitter.reviews.first.user_id) %></div>
                </div>
                <div class="bottom-info_right_top_review_content"><%= petsitter.reviews.first.content %></div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <!--ページネーション-->
      <%= paginate @petsitters %>
  </ul>
</div>

app/views/petsitters/map.html.erb
<%= render partial: 'petsitters/shopHeader' %>
<ul class="shop-menu-bar">
  <li class="shop-menu-link"><%= link_to "店舗トップ", petsitter_path %></li>
  <li class="shop-menu-link"><%= link_to "詳細", petsitter_details_path %></li>
  <li class="shop-menu-link"><%= link_to "口コミ", petsitter_reviews_path %></li>
  <li class="shop-menu-link selected-menu"><%= link_to "地図", petsitter_map_path %></li>
</ul>
<div class="shop-content">
  <!-- 地図 -->
  <div class="shop-content_map">
    <span class="petsitter-address"><%= @petsitter.address %></span>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>
  </div>
</div>

<!-- googlemapテスト -->
<!--<h2>gmap</h2>-->

<div id='map'>
</div>

<style>
    #map{
        height: 400px;
        width: 600px;
    }
</style>

<script>

    let map
    let geocoder
    let marker
    let center
    let position

    function initMap(){

        // geocoderを初期化
        geocoder = new google.maps.Geocoder()

        // 入力を取得
        let address = gon.address;

        // geocoderを使って位置情報（緯度、軽度）を取得できるようにする
        geocoder.geocode( { 'address': address}, function(results, status) {
            // マップ中心とマップの場所指定を設定
            center = results[0].geometry.location;
            position = results[0].geometry.location;

            // マップ情報を設定
            map = new google.maps.Map(document.getElementById('map'), {
                center: center,
                position: position,
                zoom: 16,
            });

            // マーカーの場所情報を設定
            let markerOptions = {
                map: map,
                center: center,
                position: position,
            };

            // マーカー情報を確定
            let marker = new google.maps.Marker(markerOptions);
        });
    }

</script>

app/views/petsitters/new.html.erb
<%= render partial: 'form', locals: { petsitter: @petsitter } %>

app/views/petsitters/postReviews.html.erb
<%= render partial: 'petsitters/shopHeader' %>

<ul class="shop-menu-bar">
  <li class="shop-menu-link"><%= link_to "店舗トップ", petsitter_path(@petsitter.id) %></li>
  <li class="shop-menu-link"><%= link_to "詳細", petsitter_details_path(@petsitter.id) %></li>
  <li class="shop-menu-link selected-menu"><%= link_to "口コミ", petsitter_reviews_path(@petsitter.id) %></li>
  <li class="shop-menu-link"><%= link_to "地図", petsitter_map_path(@petsitter.id) %></li>
</ul>

<!-- 口コミ投稿フォーム -->
<%= render partial: 'reviews/form', locals: { review: @review } %>

app/views/petsitters/reviews.html.erb
<%= render partial: 'petsitters/shopHeader' %>
<ul class="shop-menu-bar">
  <li class="shop-menu-link"><%= link_to "店舗トップ", petsitter_path %></li>
  <li class="shop-menu-link"><%= link_to "詳細", petsitter_details_path %></li>
  <li class="shop-menu-link selected-menu"><%= link_to "口コミ", petsitter_reviews_path %></li>
  <li class="shop-menu-link"><%= link_to "地図", petsitter_map_path %></li>
</ul>
<div class="shop-content">

  <!-- 口コミ -->
  <div class="shop-content_reviews">
    <div class="reviews-header">
      <div class="reviews-header_count">全&nbsp;<span class="number"><%= @petsitter.reviews.count %></span>&nbsp;件</div>
      <%= link_to "口コミを投稿する", petsitter_new_reviews_path, class: 'reviews-header_post' %>
    </div>
    <% if @petsitter.reviews %>
      <% @petsitter.reviews.each do |review| %>
        <!-- 口コミ投稿内容 -->
        <div class="reviews-box">
          <div class="reviews-box_reviews-info">
            <div class="reviews-box-user-info">
              <%= image_tag getUserByUserId(review.user_id).image.url, class:'reviews-box-user-info_photo' unless getUserByUserId(review.user_id)&.image.url.blank? %>
              <div class="reviews-box-user-info_name">
                <div class="user-info"><%= link_to "#{getUserByUserId(review.user_id).name}",user_histories_path(getUserByUserId(review.user_id)) %>さんの口コミ</div>
              </div>
            </div>
            <% if current_user != nil && review.user.id == current_user.id %>
              <div class="user-action">
                <%= link_to "編集", edit_reviews_path(review.petsitter_id, review.id) %>
                <%= link_to "削除", review_path, method: :delete, data:
                    { confirm: '本当に削除して良いですか?',
                      cancel: 'やめる',
                      commit: '削除する'}, title: '削除確認' %>
              </div>
            <% end %>
          </div>
          <div class="reviews-box_reviews-rate">
            <div class="rate-container">
              <!--星評価-->
              <div id="viewReview-star-rate-<%= review.id %>" class="shop-star-rate"></div>
              <script>
                  $('#viewReview-star-rate-<%= review.id %>').raty({
                      size: 16,
                      half: true,
                      starOff:  '<%= asset_path('star-off-little.png') %>',
                      starOn : '<%= asset_path('star-on-little.png') %>',
                      starHalf: '<%= asset_path('star-half-little.png') %>',
                      readOnly: true,
                      score: "<%= review.rate %>",
                  });
              </script>
              <div class="shop-rating"><%= review.rate %></div>
<!--              ★★★★★ 3.5-->
            </div>
          </div>
          <div class="reviews-box_reviews-body">
            <div class="reviews-box_reviews-body_date">
              <%= review.created_at.strftime('%Y/%m/%d') %>投稿
<!--              2021/01投稿-->
            </div>
            <div class="reviews-box_reviews-body_title">
              <%= review.title %>
<!--              素晴らしいペットシッター-->
            </div>
            <div class="reviews-box_reviews-body_text">
              <%= review.content %>
<!--              とても親切に対応していただきました！ありがとうございます！-->
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      まだ口コミはありません
    <% end %>
  </div>
</div>

app/views/petsitters/show.html.erb
<%= render partial: 'petsitters/shopHeader' %>
<ul class="shop-menu-bar">
  <li class="shop-menu-link selected-menu"><%= link_to "店舗トップ", petsitter_path %></li>
  <li class="shop-menu-link"><%= link_to "詳細", petsitter_details_path %></li>
  <li class="shop-menu-link"><%= link_to "口コミ", petsitter_reviews_path %></li>
  <li class="shop-menu-link"><%= link_to "地図", petsitter_map_path %></li>
</ul>
<div class="shop-content">
  <!-- 店舗トップ -->
  <div class="shop-content_top">
    <%= image_tag @petsitter.image.url, class:'top-cover-img' unless @petsitter.image.url.nil? %>
    <div class="shop-outline">
      <%= @petsitter.overview unless @petsitter.blank? %>
    </div>
  </div>
</div>