config/routes.rb
Rails.application.routes.draw do

  # topPage
  root 'tops#index'
  get 'tops/index'
  post '/tops/guest_sign_in', to: 'tops#new_guest'

  # session関連
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # ＋SNSログイン
  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'

  # user関連
  resources :users

  # petsitter関連
  resources :petsitters do
    # like(いいね)関連
    resources :likes, only: [:create, :destroy]
    # temp_save(一時保存)関連
    resources :temp_saves, only: [:create, :destroy]
  end

  get 'users/:id/histories', to: 'users#histories', as: 'user_histories'
  get 'users/:id/clips', to: 'users#clips', as: 'user_clips'
  get 'petsitters/:id/details', to: 'petsitters#details', as: 'petsitter_details'
  get 'petsitters/:id/reviews', to: 'petsitters#reviews', as: 'petsitter_reviews'
  get 'petsitters/:id/reviews/new', to: 'petsitters#postReviews', as: 'petsitter_new_reviews'
  get 'petsitters/:petsitter_id/reviews/:review_id', to: 'reviews#edit', as: 'edit_reviews'
  get 'petsitters/:id/map', to: 'petsitters#map', as: 'petsitter_map'

  # review関連
  resources :reviews, only: [:create, :update, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  protect_from_forgery :except => [:create, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit]

  def create
    # ストロングパラメーターを使用してレビューインスタンス生成
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    # 現在のユーザーがすでに該当のペットシッターにコメントをしているか確認
    is_current_user_commented = Review.find_by(user_id: current_user.id, petsitter_id: @review.petsitter_id)

    # 現在のユーザーがペットシッターにコメント済みの場合、エラーへ分岐させる
    if is_current_user_commented
      # レビュー登録失敗した場合
      flash[:alert] = 'コメントできませんでした'
      @petsitter = Petsitter.find(@review.petsitter_id)
      render  template: 'petsitters/postReviews' and return
    end

    # まだコメントしていない場合は、コメントを登録させる
    if @review.save
      # レビュー登録成功した場合
      flash[:success] = 'コメントしました'
      redirect_to petsitter_reviews_path(@review.petsitter_id)
    else
      # レビュー登録失敗した場合
      flash[:alert] = 'コメントできませんでした'
      @petsitter = Petsitter.find(@review.petsitter_id)
      render 'petsitters/postReviews'
    end
  end

  # reviewの編集
  def edit
    @review = Review.find(params[:review_id])
    @petsitter = Petsitter.find(params[:petsitter_id])
  end

  # reviewの編集実行
  def update
    @review = Review.find(params[:id])
    @petsitter = Petsitter.find(@review.petsitter_id)
    if @review.update(review_params)
      redirect_to petsitter_path(@review.petsitter_id), notice: 'レビュー情報を修正しました'
    else
      flash.now[:alert] = 'レビュー情報更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @review = Review.find_by(user_id: current_user.id)
    @review.destroy
    redirect_to petsitter_path(@review.petsitter_id), notice: 'レビュー情報を削除しました'
  end

  private
    def review_params
      params.require(:review).permit(:title,:content,:rate,:petsitter_id)
    end

    # review/editにアクセスしたユーザーがコメント投稿主か確認
    def ensure_correct_user
      review = Review.find(params[:review_id])
      if current_user.id != review.user_id.to_i
        flash[:alert] = 'コメント投稿者とログイン中ユーザーが異なります。'
        redirect_to(root_path)
      end
    end
end

app/views/reviews/_form.html.erb
<% if review&.errors.present? %>
  <ul class="form-alert">
    <% review.errors.full_messages.each do |message| %>
      <% if message.include? "Petsitter" %>
        <li><%= message.delete("Petsitter") %></li>
      <% else %>
        <li><%= message %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<!--エラーメッセージ-->
  <!-- 口コミ入力フォーム -->
  <%= form_with model: review, local: true do |f| %>
    <div class="form-box">
      <div class="form-box_title">
        <!-- タイトル -->
        <% if current_page?(petsitter_new_reviews_path(@petsitter.id)) %>
          口コミを投稿する
        <% else %>
         口コミを編集する
        <% end %>
      </div>
      <div class="form-box_review">
        <div class="form-group-row">
          <!-- 評価 -->
          <div class="rate-title">
            <%= f.label :rate , id:'test' %>
          </div>
          <div class="rate-count" id="submit-star">
            <%= f.hidden_field :rate, id: :review_star, id:'review_title', value: review&.title %>
          </div>
          <script>
              $('#submit-star').raty({
                  size     : 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  scoreName: 'review[rate]',
                  half: true,
                  score: <%= review.rate unless review == nil %>
              });
          </script>
        </div>
      </div>
      <div class="form-box_content">
        <!-- タイトル -->
        <div class="form-group-row">
          <%= f.text_field :title, class: "form-group-row_title", id:'review_title', value: review&.title,
                           placeholder:'口コミのタイトルを入力してください'%>
        </div>

        <!-- 口コミ -->
        <div class="form-group-row">
          <%= f.text_area :content, class: "form-group-row_field", rows: "8", id:'review_content', value: review&.content,
                          placeholder:'口コミ本文を入力してください' %>
        </div>

        <!--ペットシッターIDの送信-->
        <%= f.hidden_field :petsitter_id, { value: @petsitter.id } %>

      </div>
      <div class="form-box_submit">
        <!-- 確認ボタン -->
        <%= f.submit '投稿する', class:"btn-success" %>
      </div>
    </div>

  <% end %>

app/views/reviews/_show-reviews.html.erb
<% if reviews.present? %>
  <% reviews.each do |review| %>
    <div class="row reviews">
      <div class="col-md-2 reviews-user">
        <%= link_to review.user do %>
          <% if review.user.image.url %>
            <%= image_tag review.user.image.url ,width: '100px' %>
          <% end %>
        <% end %>
        <p class="reviews-title"><%= link_to review.user.name, review.user %></p>
      </div>
      <div class="col-md-6 mb-3">
        <div class=" reviews-content">
          <h4 class="mb-3">評価：<%= review.rate %>点 | <%= review.title %></h4>

          <!--星評価-->
          <div id="star-rate-<%= review.id %>"></div>
          <script>
              $('#star-rate-<%= review.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= review.rate %>,
              });
          </script>
          <!--/星評価-->

          <p><%= review.content %></p>
        </div>
      </div>
      <div class="col-md-12 edit-button">
        <% if current_user == review.user %>
          <%= link_to '口コミを編集', edit_review_path(review), method: :get, class:'btn btn-default' %>
          <%= link_to '口コミを削除', review, method: :delete, class:'btn btn-default' %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/reviews/_test.html.erb
<% unless @is_my_review %>

  <!-- 口コミ入力フォーム -->
  <%= form_with model: review, local: true do |f| %>

    <!--エラーメッセージ-->

    <!--ペットシッターIDの送信-->
    <%= f.hidden_field :petsitter_id, { value: @petsitter.id } %>

    <!-- タイトル -->
    <div class="form-group row">
      <%= f.label :title, class:'col-md-3 col-form-label' %>
      <div class="col-md-9">
        <%= f.text_field :title, class: "form-control", id:'review_title', value: review&.title %>
      </div>
    </div>

    <!-- 評価 -->
    <div class="form-group row" id="star">
      <%= f.label :rate, class:'col-md-3 col-form-label' %>
      <%= f.hidden_field :rate, id: :review_star, id:'review_title', value: review&.title %>
    </div>

    <!-- 評価javascript -->
    <script>
        $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'review[rate]',
            half: true,
            score: <%= review.rate unless review == nil %>
        });
    </script>

    <!-- 口コミ -->
    <div class="form-group row">
      <%= f.label :content, class:'col-md-3 col-form-label' %>
      <div class="col-md-9">
        <%= f.text_area :content, class: "form-control", rows: "8", id:'review_content', value: review&.content,
                        placeholder:'口コミ内容がなくても、タイトルと評価のみで投稿できます。まずは投稿してみましょう！投稿してから編集もできますよ！' %>
      </div>
    </div>

    <!-- 確認ボタン -->
    <div class="form-group row justify-content-end">
      <div class="col-md-9">
        <%= f.submit '投稿する', class:"btn btn-success" %>
      </div>
    </div>

  <% end %>

<% end %>

app/views/reviews/edit.html.erb
<%= render partial: 'petsitters/shopHeader' %>

<ul class="shop-menu-bar">
  <li class="shop-menu-link"><%= link_to "店舗トップ", petsitter_path(@petsitter.id) %></li>
  <li class="shop-menu-link"><%= link_to "詳細", petsitter_details_path(@petsitter.id) %></li>
  <li class="shop-menu-link selected-menu"><%= link_to "口コミ", petsitter_reviews_path(@petsitter.id) %></li>
  <li class="shop-menu-link"><%= link_to "地図", petsitter_map_path(@petsitter.id) %></li>
</ul>

<div class="shop-content">
  <%= render partial: 'form', locals: { review: @review } %>
</div>