config/routes.rb
Rails.application.routes.draw do

  # topPage
  root 'tops#index'
  get 'tops/index'
  post '/tops/guest_sign_in', to: 'tops#new_guest'

  # session関連
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # ＋SNSログイン
  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'

  # user関連
  resources :users

  # petsitter関連
  resources :petsitters do
    # like(いいね)関連
    resources :likes, only: [:create, :destroy]
    # temp_save(一時保存)関連
    resources :temp_saves, only: [:create, :destroy]
  end

  get 'users/:id/histories', to: 'users#histories', as: 'user_histories'
  get 'users/:id/clips', to: 'users#clips', as: 'user_clips'
  get 'petsitters/:id/details', to: 'petsitters#details', as: 'petsitter_details'
  get 'petsitters/:id/reviews', to: 'petsitters#reviews', as: 'petsitter_reviews'
  get 'petsitters/:id/reviews/new', to: 'petsitters#postReviews', as: 'petsitter_new_reviews'
  get 'petsitters/:petsitter_id/reviews/:review_id', to: 'reviews#edit', as: 'edit_reviews'
  get 'petsitters/:id/map', to: 'petsitters#map', as: 'petsitter_map'

  # review関連
  resources :reviews, only: [:create, :update, :destroy]

end

app/views/layouts/_commonHeader.html.erb
<!-- flashメッセージの表示 -->
<%= render partial: 'layouts/errorMessage' %>

<!-- トップページ以外のヘッダー -->
<header class="header">
  <div class="header_border">
    <div class="header-wrapper">
      <div class="header-wrapper_top">
        <div class="page-name"></div>
        <div class="menu">
          <ul class="menu-list">
            <% if current_user %>
              <!--              ログイン中ユーザー用メニュー-->
              <li class="menu-option"><%= link_to 'トップページ', root_path %></li>
              <li class="menu-option"><%= link_to 'ペットシッター一覧', petsitters_path %></li>
              <li class="menu-option"><%= link_to 'ユーザー詳細', user_path(current_user.id) %></li>
              <% if current_user.admin == true %>
                <li class="menu-option"><%= link_to 'ペットシッター新規作成', new_petsitter_path %></li>
              <% end %>
              <li class="menu-option"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            <% else %>
              <!--             未ログインユーザー用メニュー -->
              <li class="menu-option"><%= link_to 'トップページ', root_path %></li>
              <li class="menu-option"><%= link_to 'ペットシッター一覧', petsitters_path %></li>
              <li class="menu-option"><%= link_to '新規登録', new_user_path %></li>
              <li class="menu-option"><%= link_to 'ログイン', login_path %></li>
              <li class="menu-option"><%= link_to 'ゲストログイン', tops_guest_sign_in_path, method: :post %></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class='header-wrapper_bottom'>
        <div class='search-form'>
          <div id='app-icon-box'><%=link_to image_tag("logooo.png", class: 'header-icon' ), root_path%></div>
          <div class='search-box'>
            <%= search_form_for(@q, url:petsitters_path, class:'shop-search' ) do |f| %>
              <div class="search-container">
                <%= f.search_field :area_cont, :placeholder => "エリア[例：新宿]", class:'search-content search-container_area' %>
                <%= f.search_field :name_or_pet_type_cont, :placeholder => "キーワード[例：うさぎ or 店名など]", class:'search-content search-container_keyword' %>
                <!-- レート検索 -->
                <%= button_tag '<i class="fas fa-search fa-2x"></i>'.html_safe, :type => "submit",
                               :class=>"btn btn-default btn-s-md search-container_submit" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_commonSecondHeader.html.erb
<!-- ペットシッター詳細関連画面のヘッダー下共通部分 -->
<header class="page-header second-header-wrapper">
    <%= render "shared/breadcrumbs" %>
  <div class="cover-img">
    <%= image_tag("greenleaves.jpg" ) %>
  </div>
  <div class="content-container">
    <% if current_user.image.blank? %>
      <%= image_tag 'default.jpg', class:'test-user' %>
    <% else %>
      <%= image_tag current_user.image.url, class:'test-user' %>
    <% end %>
    <div class="user-content-area">
      <span class="user-content-area_title"><%= @user.name %>さんのマイページ</span>
      <ul class="user-content-nav">
        <li class="user-content-nav-link first-nav"><%= link_to "トップ", user_path(@user.id) %></li>
        <li class="user-content-nav-link"><%= link_to "行ったお店", user_histories_path(@user.id) %></li>
        <li class="user-content-nav-link"><%= link_to "保存済み", user_clips_path(@user.id) %></li>
        <% if ensure_current_user %>
        <li class="user-content-nav-link"><%= link_to "設定", edit_user_path(current_user) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>
<div class="user-header-line"></div>

app/views/layouts/_errorMessage.html.erb
<!-- error Message出力（application.html.erb）で使用 -->
<% if flash.notice.present? %>
  <div class="flash_wrap alert alert-success"><%= flash.notice %></div>
<% end %>
<% if flash.alert.present? %>
  <div class="flash_wrap alert alert-warning"><%= flash.alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- 以下フッター -->
<footer class="footer outer-block">
  <div class="footer_wrap">
    <div class="footer_wrap_top">
      <ul class="footer-nav">
        <li><%=link_to 'HOME', root_path %></li>
        <li><%=link_to 'PETSITTERS', petsitters_path %></li>
        <% if current_user %>
          <li><%=link_to 'USER', user_path(current_user) %></li>
        <% else %>
          <li><%=link_to 'USER', login_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="footer_wrap_bottom">
      <div class="footer-logo">
        <%= image_tag("logooo.png", class: 'logo' ) %>
      </div>
      <ul class="footer-nav-bottom">
        <li class="item"><%=link_to 'プライバシーポリシー', root_path %></li>
        <li class="item"><%=link_to 'お問い合わせ', root_path %></li>
        <li class="item"><%=link_to '作者Twitter', 'https://twitter.com/watage_lapan' %></li>
      </ul>
      <div class="footer-copyright">
        COPYRIGHT ©︎ RuiShimazaki All rights Reserved.
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_petsittersIndexHeader.html.erb
<!-- パンクズリスト -->
<div class="petsittersIndexHeaderWrap">
  <%= render "shared/petsitter_index_breadcrumbs" %>
  <div class="searched-heading-box">
    <% if @q&.conditions&.first&.values&.first&.value&.present? || @q&.conditions&.second&.values&.first&.value&.present? %>

      <!-- エリア・キーワードどちらも検索されている場合-->
      <% if @q&.conditions&.first&.values&.first&.value&.present? && @q&.conditions&.second&.values&.first&.value&.present?  %>
        '<%= @q&.conditions&.first&.values&.first&.value %>'の'<%= @q&.conditions&.second&.values&.first&.value %>'&nbsp;を含むペットシッター

        <!-- エリア検索ワードのみある場合 -->
      <% elsif @q&.conditions&.first&.values&.first&.value&.present? %>
        '<%= @q&.conditions&.first&.values&.first&.value %>'&nbsp;のペットシッター

        <!-- キーワード検索ワードのみある場合 -->
      <% elsif @q&.conditions&.second&.values&.first&.value&.present?  %>
        '<%= @q&.conditions&.second&.values&.first&.value %>'&nbsp;を含むペットシッター
      <% end %>

      &nbsp;<span class="petsitters_count"><%= @searched_petsitters_count %>件</span>

    <% else %>
      全てのペットシッター&nbsp;<span class="petsitters_count"><%= @searched_petsitters_count %>件</span>
    <% end %>
  </div>
  <div class="petsitterIndexPageNation">
    <!-- ページネーション -->
    <%= paginate @petsitters %>
  </div>
</div>

app/views/layouts/_rate.html.erb
<!--星評価-->
<div id="star-rate-<%= @petsitter.id %>"></div>
<script>
    $('#star-rate-<%= @petsitter.id %>').raty({
        size: 36,
        starOff:  '<%= asset_path('star-off-little.png') %>',
        starOn : '<%= asset_path('star-on-little.png') %>',
        starHalf: '<%= asset_path('star-half-little.png') %>',
        // half: true,
        readOnly: true,
        <% if @reviews %>
        score: "<%= @reviews.average(:rate).to_f.round(2) || 0 %>",
        <% else %>
        score: "0",
        <% end %>
    });
</script>

<div class="shop-rating">
  <% if @reviews %>
    <%= @reviews.average(:rate).to_f.round(2) || 0 %>
  <% else %>
    0
  <% end %>
</div>
<!--/星評価-->

app/views/layouts/_snsLoginBtn.html.erb
  <p>
    <%= link_to '/auth/twitter', class: "btn btn-social btn-twitter" do %>
      <span class="fab fa-twitter"></span> Twitterアカウントでログイン
    <% end %>
  </p>
  <p>
    <%= link_to '/auth/google_oauth2', class: "btn btn-social btn-google" do %>
      <span class="fab fa-google"></span> Googleアカウントでログイン
    <% end %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsitterList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ヘッダーメニュー -->
    <% if current_page?(root_path) %>
      <%= render partial: 'tops/indexHeader' %>
    <% else %>
      <%= render partial: 'layouts/commonHeader' %>
      <% if user_signed_in? %>
      <% end %>
    <% end %>

    <!-- トップページ用ボディ&フッター部分 -->
    <% if current_page?(root_path) %>
    <div id="wrap">
      <div id="index-contents">
        <h2>
          <%= yield %>
        </h2>
      </div>
      <!-- 以下、トップページ用サイドナビ -->
        <%= render partial: 'tops/sidenavi' %>
      <!-- 以下、フッター -->
    </div>
    <%= render partial: 'layouts/footer' %>
    <% end %>

    <!-- トップページ以外のボディ&フッター -->
    <% unless current_page?(root_path) %>
    <div id="wrap">
      <div id="body-contents">
        <h2>
          <%= yield %>
        </h2>
      </div>
    </div>
    <!-- 以下、フッター -->
    <%= render partial: 'layouts/footer' %>
    <% end %>
  </body>
</html>